name: Build and Deploy for Go service - OCI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  SERVICE_NAME: servb
  NAMESPACE: test-app
  CLUSTER_NAME: stage-clus
  ARTIFACT_REPO_NAME: zop-dev
  OKE_CLUSTER_ID: ocid1.cluster.oc1.ap-mumbai-1.aaaaaaaalhmiksodiukv4fqmvldccmtkwokc5nuseve6hw2gocdfjcnggdwq

jobs:
  dockerize:
    runs-on: ubuntu-latest
    name: 🐳 Dockerize
    outputs:
      image: ${{ steps.output-image.outputs.image }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Get dependencies
        run: go mod download

      - name: Build Go Binary
        run: |
          CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o main

      - name: Setup OCI CLI Config
        run: |
          mkdir -p ~/.oci

          echo '${{ secrets.OCI_SERVICE_CREDENTIALS }}' > /tmp/creds.json

          jq -r '.serviceCredentials.private_key' /tmp/creds.json | awk '{gsub(/\\n/, "\n")} 1' > ~/.oci/private_key.pem          
          chmod 600 ~/.oci/private_key.pem

          cat > ~/.oci/config <<EOF
          [DEFAULT]
          user=$(jq -r '.serviceCredentials.user_ocid' /tmp/creds.json)
          fingerprint=$(jq -r '.serviceCredentials.fingerprint' /tmp/creds.json)
          tenancy=$(jq -r '.serviceCredentials.tenancy_ocid' /tmp/creds.json)
          region=$(jq -r '.serviceCredentials.region' /tmp/creds.json)
          key_file=~/.oci/private_key.pem
          pass_phrase="N/A"
          EOF

      - name: Install OCI CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH
          source ~/.bashrc || true
      
      - name: Display OCI Config
        run: |
          echo "=== ~/.oci/config ==="
          cat ~/.oci/config
          echo "=== ~/.oci/private_key.pem ==="
          cat ~/.oci/private_key.pem
          
      - name: Test OCI CLI Access
        run: |
          oci os ns get --config-file ~/.oci/config --profile DEFAULT

      - name: Login to OCI Artifact Registry
        run: |
          REGION=$(jq -r '.serviceCredentials.region' /tmp/creds.json)
          AUTH_TOKEN=$(jq -r '.auth_token' /tmp/creds.json)
          USERNAME=$(jq -r '.username' /tmp/creds.json)

          echo "${AUTH_TOKEN}" | docker login ${REGION}.ocir.io -u "${USERNAME}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          REGION=$(jq -r '.serviceCredentials.region' /tmp/creds.json)
          IMAGE_URL="${REGION}.ocir.io/${{ env.ARTIFACT_REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}"

          docker build -t ${IMAGE_URL} .
          docker push ${IMAGE_URL}

          docker tag ${IMAGE_URL} "${REGION}.ocir.io/${{ env.ARTIFACT_REPO_NAME }}/${{ env.SERVICE_NAME }}:latest"
          docker push "${REGION}.ocir.io/${{ env.ARTIFACT_REPO_NAME }}/${{ env.SERVICE_NAME }}:latest"

      - id: output-image
        run: |
          REGION=$(jq -r '.serviceCredentials.region' /tmp/creds.json)
          echo "image=${REGION}.ocir.io/${{ env.ARTIFACT_REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}" >> "$GITHUB_OUTPUT"

  deployment:
    runs-on: ubuntu-latest
    needs: dockerize
    name: 🚀 Deploy
    env:
      image: ${{ needs.dockerize.outputs.image }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup OCI CLI Config
        run: |
          mkdir -p ~/.oci
          echo '${{ secrets.OCI_SERVICE_CREDENTIALS }}' > /tmp/creds.json

          jq -r '.serviceCredentials.private_key' /tmp/creds.json | awk '{gsub(/\\n/, "\n")} 1' > ~/.oci/private_key.pem          
          chmod 600 ~/.oci/private_key.pem

          cat > ~/.oci/config <<EOF
          [DEFAULT]
          user=$(jq -r '.serviceCredentials.user_ocid' /tmp/creds.json)
          fingerprint=$(jq -r '.serviceCredentials.fingerprint' /tmp/creds.json)
          tenancy=$(jq -r '.serviceCredentials.tenancy_ocid' /tmp/creds.json)
          region=$(jq -r '.serviceCredentials.region' /tmp/creds.json)
          key_file=~/.oci/private_key.pem
          pass_phrase="N/A"
          EOF

      - name: Install OCI CLI
        run: |
          curl -L https://raw.githubusercontent.com/oracle/oci-cli/master/scripts/install/install.sh | bash -s -- --accept-all-defaults
          echo "$HOME/bin" >> $GITHUB_PATH
          source ~/.bashrc || true

      - name: Display OCI Config
        run: |
          echo "=== ~/.oci/config ==="
          cat ~/.oci/config
          echo "=== ~/.oci/private_key.pem ==="
          cat ~/.oci/private_key.pem

      - name: Install and Configure kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Set Up OKE Kubeconfig
        run: |
          REGION=$(jq -r '.serviceCredentials.region' /tmp/creds.json)

          oci ce cluster create-kubeconfig \
            --cluster-id ${{ env.OKE_CLUSTER_ID }} \
            --file ~/.kube/config \
            --region ${REGION} \
            --token-version 2.0.0 \
            --kube-endpoint PUBLIC_ENDPOINT

      - name: Update Deployment
        run: |
          kubectl set image deployment/${{ env.SERVICE_NAME }} ${{ env.SERVICE_NAME }}=${{ env.image }} --namespace ${{ env.NAMESPACE }}

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/${{ env.SERVICE_NAME }} --namespace ${{ env.NAMESPACE }} --timeout=300s